FROM python:3.10-slim

# install libraries
COPY requirements.txt .
RUN pip install -r requirements.txt

# add repository code
WORKDIR /opt/dagster/app

# run dagster gRPC server on port 4000
EXPOSE 4000
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "pipeline.py"]
