models:
  - name: stg_kaggle__customer
    description: >
      Source Table containing data related to customers
    tests:
      - unique:
          column_name: customer_id
  - name: stg_kaggle__invoice
    description: >
      Source Table containing data related to invoices
    tests:
      - unique:
          column_name: invoice_id
