name: 'dbt_analytics'

config-version: 2
version: '0.1'

profile: 'dbt_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

flags:
  use_experimental_parser: false   # optional
  partial_parse: false             # required to disable cache folder hashing
