models:
  - name: invoice
    description: >
      Core Table that contains detailed information of invoices
    tests:
      - unique:
          column_name: invoice_key
    columns:
      - name: invoice_date
        tests:
          - not_null
      - name: invoice_id
        tests:
          - not_null
      - name: customer_key
        testes:
          - relationships:
              to: ref('customer')
              field: customer_key


  - name: customer
    description: >
      Core Table that contains detailed information of customers
    tests:
      - unique:
          column_name: customer_key
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: first_name
        tests:
          - not_null
